import argparse
import json
import re
import uuid
import zipfile
from pathlib import Path

from update_topic_classifier import insert_query_raw, replace_query_text_raw, upsert_expression


OLD_FEEDBACK_PARAMETER = "Feedback Events File (optional)"
FEEDBACK_PARAMETER = "Feedback Events JSON (optional)"
FEEDBACK_QUERY = "ExternalFeedbackEvents"
FEEDBACK_PARAMETER_LINEAGE = str(
    uuid.uuid5(uuid.NAMESPACE_URL, "https://github.com/microsoft/ESS/parameters/feedback-events-file")
)
FEEDBACK_QUERY_LINEAGE = str(
    uuid.uuid5(uuid.NAMESPACE_URL, "https://github.com/microsoft/ESS/queries/external-feedback-events")
)
FEEDBACK_PARAMETER_EXPRESSION = (
    'null meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=false]'
)
FEEDBACK_PARAMETER_DESCRIPTION = (
    "Optional. Paste the contents of feedback-events.json generated by "
    "tools/ess_feedback_normalizer.py. This avoids cross-source privacy conflicts."
)
FEEDBACK_DIAGNOSTIC_COLUMNS = (
    ("FeedbackEventKey", "string"),
    ("ConversationId", "string"),
    ("AgentId", "string"),
    ("Channel", "string"),
    ("FeedbackSource", "string"),
    ("FeedbackVerdict", "string"),
    ("MatchStatus", "string"),
)


def build_external_feedback_query() -> str:
    return f'''let
    Empty = #table(
        type table [
            FeedbackEventId = nullable text,
            ConversationId = nullable text,
            AgentId = nullable text,
            AgentName = nullable text,
            Channel = nullable text,
            FeedbackSource = nullable text,
            FeedbackVerdict = nullable text,
            FeedbackComment = nullable text,
            SubmittedUtc = nullable text,
            UserId = nullable text,
            UserEmail = nullable text,
            Prompt = nullable text,
            Response = nullable text,
            App = nullable text,
            AppLanguage = nullable text,
            Platform = nullable text,
            SourceType = nullable text,
            AdditionalMetadata = nullable text,
            MatchStatus = nullable text
        ],
        {{}}
    ),
    SourceValue = try Text.From(#"{FEEDBACK_PARAMETER}") otherwise "",
    SourceText = if SourceValue = null then "" else Text.Trim(SourceValue),
    Parsed =
        if SourceText = "" then {{}}
        else try Json.Document(Text.ToBinary(SourceText, TextEncoding.Utf8))
             otherwise error "Feedback Events JSON is invalid. Regenerate feedback-events.json with ess_feedback_normalizer.py.",
    Checked =
        if not Value.Is(Parsed, type list) then
            error "Feedback Events JSON must contain a JSON array."
        else Parsed,
    Records = List.Select(Checked, each Value.Is(_, type record)),
    Loaded =
        if List.IsEmpty(Records) then Empty
        else Table.FromRecords(
            Records,
            type table [
                FeedbackEventId = nullable text,
                ConversationId = nullable text,
                AgentId = nullable text,
                AgentName = nullable text,
                Channel = nullable text,
                FeedbackSource = nullable text,
                FeedbackVerdict = nullable text,
                FeedbackComment = nullable text,
                SubmittedUtc = nullable text,
                UserId = nullable text,
                UserEmail = nullable text,
                Prompt = nullable text,
                Response = nullable text,
                App = nullable text,
                AppLanguage = nullable text,
                Platform = nullable text,
                SourceType = nullable text,
                AdditionalMetadata = nullable text,
                MatchStatus = nullable text
            ],
            MissingField.UseNull
        )
in
    Loaded
'''


def build_conversation_feedback_query() -> str:
    return '''let
    Source = #"Agent Performance",
    KnownConversations = Table.Buffer(
        Table.SelectColumns(Source, {"ConversationTranscriptId", "BotId", "BotName"})
    ),
    WithFeedback = Table.SelectRows(Source, each [Feedback] <> null and [Feedback] <> ""),
    TranscriptMapped = Table.AddColumn(WithFeedback, "_fb", each [
        FeedbackId            = [ConversationTranscriptId],
        Comment               = [FeedbackComment],
        TranslatedComment     = null,
        CommentLanguage       = null,
        DateSubmittedUTC      = [SessionEndTimeUtc],
        FeedbackType          = [Feedback],
        ResponseStatus        = "Completed",
        App                   = [BotName],
        AppLanguage           = [Locale],
        Platform              = "Copilot Studio",
        SourceType            = "Conversation Transcript",
        HasLogsAttachments    = null,
        UserId                = [UserIdentity],
        UserEmail             = [UserIdentity],
        Browser               = null,
        BrowserVersion        = null,
        AIContextPrompt       = [LastUserMessage],
        AIContextResponse     = [LastBotMessage],
        SurveyQuestion        = null,
        SurveyResponseOption  = null,
        FeedbackDate          = [SessionEndTimeUtc],
        HasComment            = if [FeedbackComment] <> null and [FeedbackComment] <> "" then 1 else 0,
        PromptLength          = if [LastUserMessage] <> null then Text.Length([LastUserMessage]) else 0,
        IsAgentInteraction    = true,
        AgentName             = [BotName],
        UiHost                = null,
        CopilotType           = "Copilot Studio",
        AiAgentType           = null,
        FeedbackEventKey      = "Transcript|" & Text.From([ConversationTranscriptId]) & "|" & Text.Lower(Text.From([Feedback])),
        ConversationId       = Text.From([ConversationTranscriptId]),
        AgentId               = [BotId],
        Channel               = "Copilot Studio",
        FeedbackSource        = "Conversation Transcript",
        FeedbackVerdict       = [Feedback],
        MatchStatus           = "Native transcript"
    ]),
    TranscriptPicked = Table.SelectColumns(TranscriptMapped, {"_fb"}),
    TranscriptEvents = Table.ExpandRecordColumn(TranscriptPicked, "_fb",
        {"FeedbackId","Comment","TranslatedComment","CommentLanguage","DateSubmittedUTC","FeedbackType","ResponseStatus","App","AppLanguage","Platform","SourceType","HasLogsAttachments","UserId","UserEmail","Browser","BrowserVersion","AIContextPrompt","AIContextResponse","SurveyQuestion","SurveyResponseOption","FeedbackDate","HasComment","PromptLength","IsAgentInteraction","AgentName","UiHost","CopilotType","AiAgentType","FeedbackEventKey","ConversationId","AgentId","Channel","FeedbackSource","FeedbackVerdict","MatchStatus"}),

    ExternalJoined = Table.NestedJoin(
        ExternalFeedbackEvents,
        {"ConversationId"},
        KnownConversations,
        {"ConversationTranscriptId"},
        "_session",
        JoinKind.LeftOuter
    ),
    ExternalExpanded = Table.ExpandTableColumn(
        ExternalJoined,
        "_session",
        {"BotId", "BotName"},
        {"MatchedBotId", "MatchedBotName"}
    ),
    ExternalMapped = Table.AddColumn(ExternalExpanded, "_fb", each
        let
            submitted = try DateTimeZone.RemoveZone(DateTimeZone.FromText([SubmittedUtc]))
                        otherwise try DateTime.From([SubmittedUtc])
                        otherwise null,
            matched = [MatchedBotId] <> null or [MatchedBotName] <> null,
            eventId = if [FeedbackEventId] = null or Text.Trim([FeedbackEventId]) = ""
                      then Text.From([ConversationId]) & "|" & Text.From([FeedbackVerdict])
                      else [FeedbackEventId]
        in [
            FeedbackId            = eventId,
            Comment               = [FeedbackComment],
            TranslatedComment     = null,
            CommentLanguage       = null,
            DateSubmittedUTC      = submitted,
            FeedbackType          = [FeedbackVerdict],
            ResponseStatus        = "Completed",
            App                   = if [App] <> null and Text.Trim([App]) <> "" then [App]
                                    else if [AgentName] <> null and Text.Trim([AgentName]) <> "" then [AgentName]
                                    else [MatchedBotName],
            AppLanguage           = [AppLanguage],
            Platform              = if [Platform] <> null and Text.Trim([Platform]) <> "" then [Platform] else [Channel],
            SourceType            = [SourceType],
            HasLogsAttachments    = null,
            UserId                = [UserId],
            UserEmail             = [UserEmail],
            Browser               = null,
            BrowserVersion        = null,
            AIContextPrompt       = [Prompt],
            AIContextResponse     = [Response],
            SurveyQuestion        = null,
            SurveyResponseOption  = null,
            FeedbackDate          = submitted,
            HasComment            = if [FeedbackComment] <> null and [FeedbackComment] <> "" then 1 else 0,
            PromptLength          = if [Prompt] <> null then Text.Length([Prompt]) else 0,
            IsAgentInteraction    = [AgentId] <> null or [AgentName] <> null or matched,
            AgentName             = if [AgentName] <> null and Text.Trim([AgentName]) <> "" then [AgentName] else [MatchedBotName],
            UiHost                = [Channel],
            CopilotType           = if [Channel] = "Microsoft 365 Copilot Chat" then "Microsoft 365 Copilot"
                                    else if [Channel] = "Microsoft Teams" then "Microsoft Teams"
                                    else "Copilot Studio",
            AiAgentType           = null,
            FeedbackEventKey      = "External|" & Text.From(eventId),
            ConversationId       = [ConversationId],
            AgentId               = if [AgentId] <> null and Text.Trim([AgentId]) <> "" then [AgentId] else [MatchedBotId],
            Channel               = [Channel],
            FeedbackSource        = [FeedbackSource],
            FeedbackVerdict       = [FeedbackVerdict],
            MatchStatus           = if matched then "Exact conversation match" else [MatchStatus]
        ]),
    ExternalPicked = Table.SelectColumns(ExternalMapped, {"_fb"}),
    ExternalEvents = Table.ExpandRecordColumn(ExternalPicked, "_fb",
        {"FeedbackId","Comment","TranslatedComment","CommentLanguage","DateSubmittedUTC","FeedbackType","ResponseStatus","App","AppLanguage","Platform","SourceType","HasLogsAttachments","UserId","UserEmail","Browser","BrowserVersion","AIContextPrompt","AIContextResponse","SurveyQuestion","SurveyResponseOption","FeedbackDate","HasComment","PromptLength","IsAgentInteraction","AgentName","UiHost","CopilotType","AiAgentType","FeedbackEventKey","ConversationId","AgentId","Channel","FeedbackSource","FeedbackVerdict","MatchStatus"}),

    ExternalDeduplicated = Table.Distinct(Table.Buffer(ExternalEvents), {"FeedbackEventKey"}),
    ExternalWithPairKey = Table.AddColumn(
        ExternalDeduplicated,
        "_ConversationVerdictKey",
        each if [ConversationId] <> null and Text.Trim(Text.From([ConversationId])) <> ""
             then "Conversation|" & Text.Lower(Text.From([ConversationId])) & "|" & Text.Lower(Text.From([FeedbackVerdict]))
             else null,
        type nullable text
    ),
    ExternalPairKeys = List.Buffer(List.RemoveNulls(Table.Column(ExternalWithPairKey, "_ConversationVerdictKey"))),
    TranscriptWithPairKey = Table.AddColumn(
        TranscriptEvents,
        "_ConversationVerdictKey",
        each "Conversation|" & Text.Lower(Text.From([ConversationId])) & "|" & Text.Lower(Text.From([FeedbackVerdict])),
        type text
    ),
    TranscriptWithoutExportedCopies = Table.SelectRows(
        TranscriptWithPairKey,
        each not List.Contains(ExternalPairKeys, [_ConversationVerdictKey])
    ),
    Combined = Table.Combine({ExternalWithPairKey, TranscriptWithoutExportedCopies}),
    RemovedPairKey = Table.RemoveColumns(Combined, {"_ConversationVerdictKey"}),
    Typed = Table.TransformColumnTypes(RemovedPairKey, {
        {"DateSubmittedUTC", type datetime},
        {"FeedbackDate", type datetime},
        {"HasComment", Int64.Type},
        {"PromptLength", Int64.Type},
        {"IsAgentInteraction", type logical}
    }, "en-US")
in
    Typed
'''


def add_model_columns(table: dict, columns: tuple[tuple[str, str], ...], namespace: str) -> None:
    existing = {column["name"] for column in table.get("columns", [])}
    for name, data_type in columns:
        if name in existing:
            continue
        table["columns"].append(
            {
                "name": name,
                "dataType": data_type,
                "sourceColumn": name,
                "lineageTag": str(uuid.uuid5(uuid.NAMESPACE_URL, f"{namespace}/{name}")),
                "summarizeBy": "none",
                "annotations": [{"name": "SummarizationSetBy", "value": "Automatic"}],
            }
        )


def set_partition_expression(model: dict, table_name: str, expression: str) -> None:
    table = next(table for table in model["tables"] if table["name"] == table_name)
    source = table["partitions"][0]["source"]
    original = source["expression"]
    source["expression"] = expression.splitlines() if isinstance(original, list) else expression


def rename_query_raw(raw: str, old_name: str, new_name: str) -> str:
    document = json.loads(raw)
    if any(item["name"] == new_name for item in document["queries"]):
        return raw
    if not any(item["name"] == old_name for item in document["queries"]):
        return raw
    old_encoded = '"name":' + json.dumps(old_name, ensure_ascii=False)
    new_encoded = '"name":' + json.dumps(new_name, ensure_ascii=False)
    position = raw.find(old_encoded)
    if position < 0:
        raise ValueError(f"Unapplied query name not found: {old_name}")
    return raw[:position] + new_encoded + raw[position + len(old_encoded) :]


def patch_direct_feedback_measures(model: dict) -> None:
    expressions = {
        ("Agent Performance", "Chat Thumbs Up Count"): (
            'CALCULATE(COUNTROWS(\'ConversationFeedback\'), '
            '\'ConversationFeedback\'[FeedbackType] = "Thumbs Up")'
        ),
        ("Agent Performance", "Chat Thumbs Down Count"): (
            'CALCULATE(COUNTROWS(\'ConversationFeedback\'), '
            '\'ConversationFeedback\'[FeedbackType] = "Thumbs Down")'
        ),
        ("Agent Performance", "Feedback Responses"): "COUNTROWS('ConversationFeedback')",
        ("Agent Performance", "Feedback Response Rate"): (
            "VAR MatchedFeedback =\n"
            "    CALCULATE(\n"
            "        DISTINCTCOUNT('ConversationFeedback'[ConversationId]),\n"
            "        KEEPFILTERS(\n"
            "            'ConversationFeedback'[MatchStatus] IN "
            "{\"Native transcript\", \"Exact conversation match\"}\n"
            "        )\n"
            "    )\n"
            "RETURN DIVIDE(MatchedFeedback, [Conversations], 0)"
        ),
        ("ConversationFeedback", "Total Feedback"): "COUNTROWS('ConversationFeedback')",
        ("ConversationFeedback", "Thumbs Up Count"): (
            'CALCULATE(COUNTROWS(\'ConversationFeedback\'), '
            '\'ConversationFeedback\'[FeedbackType] = "Thumbs Up")'
        ),
        ("ConversationFeedback", "Thumbs Down Count"): (
            'CALCULATE(COUNTROWS(\'ConversationFeedback\'), '
            '\'ConversationFeedback\'[FeedbackType] = "Thumbs Down")'
        ),
        ("ConversationFeedback", "Satisfaction Rate"): (
            "DIVIDE(\n"
            "    CALCULATE(COUNTROWS('ConversationFeedback'), "
            "'ConversationFeedback'[FeedbackType] = \"Thumbs Up\"),\n"
            "    CALCULATE(COUNTROWS('ConversationFeedback'), "
            "'ConversationFeedback'[FeedbackType] IN {\"Thumbs Up\", \"Thumbs Down\"}),\n"
            "    0\n"
            ")"
        ),
        ("ConversationFeedback", "Thumbs Up Rate"): (
            "DIVIDE(\n"
            "    CALCULATE(COUNTROWS('ConversationFeedback'), "
            "'ConversationFeedback'[FeedbackType] = \"Thumbs Up\"),\n"
            "    CALCULATE(COUNTROWS('ConversationFeedback'), "
            "'ConversationFeedback'[FeedbackType] IN {\"Thumbs Up\", \"Thumbs Down\"}),\n"
            "    BLANK()\n"
            ")"
        ),
    }
    for (table_name, measure_name), expression in expressions.items():
        table = next(table for table in model["tables"] if table["name"] == table_name)
        measure = next(
            (measure for measure in table.get("measures", []) if measure["name"] == measure_name),
            None,
        )
        if measure is None:
            raise ValueError(f"Feedback measure not found: {table_name}[{measure_name}]")
        measure["expression"] = expression


def patch_direct_pbit(source: Path, destination: Path) -> None:
    external_query = build_external_feedback_query()
    feedback_query = build_conversation_feedback_query()
    with zipfile.ZipFile(source, "r") as archive:
        infos = archive.infolist()
        parts = {info.filename: archive.read(info.filename) for info in infos}

    schema = json.loads(parts["DataModelSchema"].decode("utf-16-le"))
    model = schema["model"]
    old_parameter = next(
        (item for item in model["expressions"] if item["name"] == OLD_FEEDBACK_PARAMETER),
        None,
    )
    if old_parameter and not any(
        item["name"] == FEEDBACK_PARAMETER for item in model["expressions"]
    ):
        old_parameter["name"] = FEEDBACK_PARAMETER
    upsert_expression(
        model,
        {
            "name": FEEDBACK_PARAMETER,
            "description": FEEDBACK_PARAMETER_DESCRIPTION,
            "kind": "m",
            "expression": FEEDBACK_PARAMETER_EXPRESSION,
            "lineageTag": FEEDBACK_PARAMETER_LINEAGE,
            "annotations": [
                {"name": "PBI_NavigationStepName", "value": "Navigation"},
                {"name": "PBI_ResultType", "value": "Text"},
            ],
        },
        "TopicRules",
    )
    upsert_expression(
        model,
        {
            "name": FEEDBACK_QUERY,
            "kind": "m",
            "expression": external_query,
            "lineageTag": FEEDBACK_QUERY_LINEAGE,
            "annotations": [{"name": "PBI_ResultType", "value": "List"}],
        },
        "TopicRules",
    )
    set_partition_expression(model, "ConversationFeedback", feedback_query)
    patch_direct_feedback_measures(model)
    feedback_table = next(table for table in model["tables"] if table["name"] == "ConversationFeedback")
    add_model_columns(
        feedback_table,
        FEEDBACK_DIAGNOSTIC_COLUMNS,
        "https://github.com/microsoft/ESS/feedback",
    )
    parts["DataModelSchema"] = json.dumps(schema, ensure_ascii=False, separators=(",", ":")).encode("utf-16-le")

    raw = parts["UnappliedChanges"].decode("utf-16-le")
    raw = rename_query_raw(raw, OLD_FEEDBACK_PARAMETER, FEEDBACK_PARAMETER)
    raw = insert_query_raw(
        raw,
        {
            "name": FEEDBACK_PARAMETER,
            "lineageTag": FEEDBACK_PARAMETER_LINEAGE,
            "description": FEEDBACK_PARAMETER_DESCRIPTION,
            "navigationStepName": "Navigation",
            "text": [FEEDBACK_PARAMETER_EXPRESSION],
            "loadAsTableDisabled": True,
            "resultType": "Text",
            "isHidden": False,
        },
    )
    raw = insert_query_raw(
        raw,
        {
            "name": FEEDBACK_QUERY,
            "lineageTag": FEEDBACK_QUERY_LINEAGE,
            "text": external_query.splitlines(),
            "loadAsTableDisabled": True,
            "resultType": "List",
            "isHidden": False,
        },
    )
    raw = replace_query_text_raw(raw, FEEDBACK_PARAMETER, lambda _: FEEDBACK_PARAMETER_EXPRESSION)
    raw = replace_query_text_raw(raw, FEEDBACK_QUERY, lambda _: external_query)
    raw = replace_query_text_raw(raw, "ConversationFeedback", lambda _: feedback_query)
    json.loads(raw)
    parts["UnappliedChanges"] = raw.encode("utf-16-le")

    destination.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(destination, "w", zipfile.ZIP_DEFLATED) as archive:
        for info in infos:
            archive.writestr(info, parts[info.filename])


def build_fabric_feedback_block() -> str:
    return r'''# --- Unified feedback events: transcript reactions + normalized external exports ---
_USER_FEEDBACK_COLUMNS = [
    'Feedback Id', 'Comment', 'Translated Comment', 'Comment Language', 'Date Submitted UTC',
    'Feedback Type', 'Microsoft Response Status', 'App', 'App Language', 'Platform', 'Source Type',
    'Logs, Attachments', 'User Id', 'User Email', 'Browser', 'Browser Version', 'AI Context Prompt',
    'AI Context Response Message', 'Survey Question', 'Survey Response Option', 'Additional Metadata',
    'Date Submitted Date', 'Sentiment', 'Feedback Event Key', 'Conversation Id', 'Agent Id', 'Channel',
    'Feedback Source', 'Feedback Verdict', 'Match Status'
]

def _feedback_metadata(conversation_id, agent_id, agent_name, channel, existing=''):
    if existing:
        return existing
    copilot_type = 'm365' if channel == 'Microsoft 365 Copilot Chat' else 'custom'
    return json.dumps({
        'conversationId': conversation_id or '',
        'essAgentId': agent_id or '',
        'aiAgents': [{'Name': agent_name or '', 'Type': 'Custom'}],
        'copilotType': copilot_type,
        'UiHost': channel or '',
    }, ensure_ascii=False)

def build_user_feedback(session_frame, external_path):
    rows = []
    def _text(value):
        return '' if value is None or pd.isna(value) else str(value)

    known = {
        _text(row.get('conversation_id')): row
        for _, row in session_frame.iterrows()
        if _text(row.get('conversation_id'))
    }

    from pathlib import Path as _Path
    if external_path and _Path(external_path).exists():
        external = pd.read_csv(external_path, keep_default_na=False)
        required = {
            'FeedbackEventId', 'ConversationId', 'AgentId', 'AgentName', 'Channel',
            'FeedbackSource', 'FeedbackVerdict', 'FeedbackComment', 'SubmittedUtc',
            'UserId', 'UserEmail', 'Prompt', 'Response', 'App', 'AppLanguage',
            'Platform', 'SourceType', 'AdditionalMetadata', 'MatchStatus'
        }
        missing = sorted(required - set(external.columns))
        if missing:
            raise ValueError(f'Feedback events file is missing columns: {missing}')
        for _, item in external.iterrows():
            conversation_id = str(item['ConversationId'] or '')
            matched = known.get(conversation_id)
            agent_id = str(item['AgentId'] or '') or (str(matched.get('agent_id') or '') if matched is not None else '')
            agent_name = str(item['AgentName'] or '') or (str(matched.get('agent_name') or '') if matched is not None else '')
            channel = str(item['Channel'] or '') or 'Unknown'
            event_id = str(item['FeedbackEventId'] or '') or f'{conversation_id}|{item["FeedbackVerdict"]}'
            metadata = _feedback_metadata(
                conversation_id, agent_id, agent_name, channel, str(item['AdditionalMetadata'] or ''))
            rows.append({
                'Feedback Id': event_id,
                'Comment': str(item['FeedbackComment'] or ''),
                'Translated Comment': '',
                'Comment Language': '',
                'Date Submitted UTC': str(item['SubmittedUtc'] or ''),
                'Feedback Type': str(item['FeedbackVerdict'] or ''),
                'Microsoft Response Status': 'Completed',
                'App': str(item['App'] or '') or agent_name,
                'App Language': str(item['AppLanguage'] or ''),
                'Platform': str(item['Platform'] or '') or channel,
                'Source Type': str(item['SourceType'] or ''),
                'Logs, Attachments': '',
                'User Id': str(item['UserId'] or ''),
                'User Email': str(item['UserEmail'] or ''),
                'Browser': '',
                'Browser Version': '',
                'AI Context Prompt': str(item['Prompt'] or ''),
                'AI Context Response Message': str(item['Response'] or ''),
                'Survey Question': '',
                'Survey Response Option': '',
                'Additional Metadata': metadata,
                'Date Submitted Date': str(item['SubmittedUtc'] or '')[:10],
                'Sentiment': str(item['FeedbackVerdict'] or ''),
                'Feedback Event Key': f'External|{event_id}',
                'Conversation Id': conversation_id,
                'Agent Id': agent_id,
                'Channel': channel,
                'Feedback Source': str(item['FeedbackSource'] or ''),
                'Feedback Verdict': str(item['FeedbackVerdict'] or ''),
                'Match Status': 'Exact conversation match' if matched is not None else str(item['MatchStatus'] or ''),
                '_source_rank': 0,
            })
    elif external_path:
        print(f'External feedback events not found at {external_path}; using transcript reactions only.')

    for _, item in session_frame.iterrows():
        verdict = _text(item.get('feedback_verdict')).strip()
        if not verdict:
            continue
        display_verdict = ('Thumbs Up' if verdict == 'Positive'
                           else 'Thumbs Down' if verdict == 'Negative'
                           else verdict)
        conversation_id = _text(item.get('conversation_id'))
        agent_id = _text(item.get('agent_id'))
        agent_name = _text(item.get('agent_name'))
        submitted = _text(item.get('session_start_utc'))
        rows.append({
            'Feedback Id': conversation_id,
            'Comment': _text(item.get('feedback_comment')),
            'Translated Comment': '',
            'Comment Language': '',
            'Date Submitted UTC': submitted,
            'Feedback Type': display_verdict,
            'Microsoft Response Status': 'Completed',
            'App': agent_name,
            'App Language': _text(item.get('locale')),
            'Platform': 'Copilot Studio',
            'Source Type': 'Conversation Transcript',
            'Logs, Attachments': '',
            'User Id': _text(item.get('user_id_hash')),
            'User Email': '',
            'Browser': '',
            'Browser Version': '',
            'AI Context Prompt': _text(item.get('first_user_prompt')),
            'AI Context Response Message': '',
            'Survey Question': '',
            'Survey Response Option': '',
            'Additional Metadata': _feedback_metadata(
                conversation_id, agent_id, agent_name, 'Copilot Studio'),
            'Date Submitted Date': submitted[:10],
            'Sentiment': 'Positive' if display_verdict == 'Thumbs Up' else 'Negative' if display_verdict == 'Thumbs Down' else display_verdict,
            'Feedback Event Key': f'Transcript|{conversation_id}|{display_verdict.lower()}',
            'Conversation Id': conversation_id,
            'Agent Id': agent_id,
            'Channel': 'Copilot Studio',
            'Feedback Source': 'Conversation Transcript',
            'Feedback Verdict': display_verdict,
            'Match Status': 'Native transcript',
            '_source_rank': 1,
        })

    if not rows:
        return pd.DataFrame(columns=_USER_FEEDBACK_COLUMNS)
    frame = pd.DataFrame(rows)
    external = (frame[frame['_source_rank'] == 0]
                .drop_duplicates('Feedback Event Key', keep='first'))
    transcript = frame[frame['_source_rank'] == 1].copy()
    external_pairs = {
        (str(row['Conversation Id']).lower(), str(row['Feedback Verdict']).lower())
        for _, row in external.iterrows()
        if str(row['Conversation Id'] or '')
    }
    transcript = transcript[
        ~transcript.apply(
            lambda row: (
                str(row['Conversation Id']).lower(),
                str(row['Feedback Verdict']).lower()) in external_pairs,
            axis=1)]
    frame = pd.concat([external, transcript], ignore_index=True)
    return frame[_USER_FEEDBACK_COLUMNS].reset_index(drop=True)

user_feedback = build_user_feedback(sessions, FEEDBACK_EVENTS_FILE)
print(f'unified feedback events: {len(user_feedback):,}')
'''


def patch_fabric_feedback_helpers(source: str) -> str:
    marker = "        # Canonical messageReaction activity writes reaction/comment under value.\n"
    if marker in source:
        return source
    insertion_point = "        val = a.get('value') if isinstance(a.get('value'), dict) else {}\n"
    if insertion_point not in source:
        raise ValueError("Fabric feedback helper insertion marker not found")
    block = marker + """        if a.get('type') == 'messageReaction':
            reaction_value = a.get('value') if isinstance(a.get('value'), dict) else {}
            v = _verdict_from_value(
                reaction_value.get('reaction')
                or reaction_value.get('reactionType')
                or a.get('reaction'))
            if v:
                verdict = v
            comment = (
                comment
                or reaction_value.get('comment')
                or reaction_value.get('feedbackText')
                or reaction_value.get('text'))
"""
    return source.replace(insertion_point, block + insertion_point, 1)


def patch_fabric_session_outcomes(source: str) -> str:
    marker = "        # Authoritative Copilot Studio SessionInfo outcome.\n"
    if marker not in source:
        insertion_point = "        verdict, comment = extract_submitted_feedback(acts)\n"
        if insertion_point not in source:
            raise ValueError("Fabric session outcome insertion marker not found")
        block = insertion_point + marker + """        session_info_values = [
            a.get('value') or {}
            for a in acts
            if isinstance(a, dict)
            and (a.get('valueType') == 'SessionInfo' or a.get('name') == 'SessionInfo')
            and isinstance(a.get('value'), dict)]
        session_info = session_info_values[-1] if session_info_values else {}
        session_outcome_raw = str(
            session_info.get('outcome')
            or session_info.get('lastSessionOutcome')
            or '').strip()
        session_outcome_map = {
            'resolved': 'Resolved',
            'escalated': 'Escalated',
            'abandon': 'Abandoned',
            'abandoned': 'Abandoned',
        }
        session_outcome_explicit = session_outcome_map.get(
            session_outcome_raw.lower(), session_outcome_raw or None)
        session_outcome_reason_explicit = (
            session_info.get('outcomeReason')
            or session_info.get('lastSessionOutcomeReason'))
"""
        source = source.replace(insertion_point, block, 1)
    source = source.replace(
        "'session_outcome_explicit': None,",
        "'session_outcome_explicit': session_outcome_explicit,",
    ).replace(
        "'session_outcome_reason_explicit': None,",
        "'session_outcome_reason_explicit': session_outcome_reason_explicit,",
    ).replace(
        "# Outcome / topic columns: explicit outcome is set by Copilot Studio only when\n"
        "            # configured; left null here (the dashboard's DAX derives outcome/topics). These\n"
        "            # columns must exist so the model's measures bind. Matches the M parser contract.",
        "# Preserve the authoritative SessionInfo outcome; downstream heuristics apply only when absent.",
    )
    return source


def patch_fabric_agent_performance_outcomes(source: str) -> str:
    marker = "        # --- Native outcome first; heuristics only when SessionInfo is absent. ---\n"
    old_block = """        # --- Heuristics ---
        engaged = bool(topics) or len(bot_msgs) > 0
        session_type = 'Engaged' if engaged else 'Unengaged'
        if connected_agents:
            outcome = 'Escalated'
        elif not engaged or (len(user_msgs) > 0 and len(bot_msgs) == 0) or (sys_error and len(bot_msgs) == 0):
            outcome = 'Abandoned'
        else:
            outcome = 'Resolved'
        outcome_reason = ('SystemError' if sys_error else 'UserError' if user_error else
                          ('Escalated' if outcome == 'Escalated' else
                           'Abandoned' if outcome == 'Abandoned' else 'Completed'))
        implied_success = 'TRUE' if (outcome == 'Resolved' and not sys_error) else 'FALSE'
"""
    new_block = marker + """        session_info_values = [
            a.get('value') or {}
            for a in acts
            if isinstance(a, dict)
            and (a.get('valueType') == 'SessionInfo' or a.get('name') == 'SessionInfo')
            and isinstance(a.get('value'), dict)]
        session_info = session_info_values[-1] if session_info_values else {}
        explicit_outcome_raw = str(
            session_info.get('outcome')
            or session_info.get('lastSessionOutcome')
            or '').strip()
        explicit_outcome = {
            'resolved': 'Resolved',
            'escalated': 'Escalated',
            'abandon': 'Abandoned',
            'abandoned': 'Abandoned',
        }.get(explicit_outcome_raw.lower(), explicit_outcome_raw or None)
        explicit_reason = (
            session_info.get('outcomeReason')
            or session_info.get('lastSessionOutcomeReason'))
        engaged = bool(topics) or len(bot_msgs) > 0
        if explicit_outcome:
            outcome = explicit_outcome
            session_type = str(session_info.get('type') or ('Engaged' if engaged else 'Unengaged'))
        else:
            session_type = 'Engaged' if engaged else 'Unengaged'
            if connected_agents:
                outcome = 'Escalated'
            elif not engaged or (len(user_msgs) > 0 and len(bot_msgs) == 0) or (sys_error and len(bot_msgs) == 0):
                outcome = 'Abandoned'
            else:
                outcome = 'Engaged-Unclassified'
        outcome_reason = explicit_reason or (
            'SystemError' if sys_error else 'UserError' if user_error else
            ('Escalated' if outcome == 'Escalated' else
             'Abandoned' if outcome == 'Abandoned' else 'NoExplicitOutcome'))
        explicit_success = session_info.get('impliedSuccess')
        if explicit_success is None:
            implied_success = 'TRUE' if (outcome == 'Resolved' and not sys_error) else 'FALSE'
        else:
            implied_success = 'TRUE' if bool(explicit_success) else 'FALSE'
"""
    if marker in source:
        start = source.index(marker)
        end = source.index("        start_iso =", start)
        source = source[:start] + new_block + "\n" + source[end:]
    else:
        if old_block not in source:
            raise ValueError("Fabric Agent Performance heuristic block not found")
        source = source.replace(old_block, new_block, 1)
    source = source.replace(
        "'SessionOutcomeExplicit': None,",
        "'SessionOutcomeExplicit': explicit_outcome,",
    ).replace(
        "'SessionOutcomeReasonExplicit': None,",
        "'SessionOutcomeReasonExplicit': explicit_reason,",
    )
    return source


def patch_fabric_notebook(path: Path) -> None:
    notebook = json.loads(path.read_text(encoding="utf-8"))
    config = "".join(notebook["cells"][3]["source"])
    if "FEEDBACK_EVENTS_FILE" not in config:
        marker = (
            "TOPIC_OVERRIDES_FILE = '/lakehouse/default/Files/config/customer-topic-overrides.csv'  "
            "# optional output from tools/ess_topic_tuner.py\n"
        )
        if marker not in config:
            raise ValueError("Fabric topic override config marker not found")
        config = config.replace(
            marker,
            marker
            + "FEEDBACK_EVENTS_FILE = '/lakehouse/default/Files/feedback/feedback-events.csv'  "
            "# optional output from tools/ess_feedback_normalizer.py\n",
            1,
        )
        notebook["cells"][3]["source"] = config.splitlines(True)

    helpers = patch_fabric_feedback_helpers("".join(notebook["cells"][10]["source"]))
    sessions = patch_fabric_session_outcomes("".join(notebook["cells"][12]["source"]))
    performance = patch_fabric_agent_performance_outcomes(
        "".join(notebook["cells"][25]["source"])
    )
    notebook["cells"][10]["source"] = helpers.splitlines(True)
    notebook["cells"][12]["source"] = sessions.splitlines(True)
    notebook["cells"][25]["source"] = performance.splitlines(True)

    writes = "".join(notebook["cells"][27]["source"])
    marker = "outputs = {\n"
    block = build_fabric_feedback_block()
    block_marker = "# --- Unified feedback events:"
    block_end_marker = "print(f'unified feedback events: {len(user_feedback):,}')"
    if block_marker in writes:
        start = writes.index(block_marker)
        end = writes.index(block_end_marker, start) + len(block_end_marker)
        writes = (
            writes[:start].rstrip()
            + "\n\n"
            + block.rstrip()
            + "\n\n"
            + writes[end:].lstrip()
        )
    else:
        if marker not in writes:
            raise ValueError("Fabric outputs marker not found")
        writes = writes.replace(marker, block.rstrip() + "\n\n" + marker, 1)
    if "    'user_feedback':" not in writes:
        writes = writes.replace(
            "    'agent_performance':  agent_performance,\n",
            "    'agent_performance':  agent_performance,\n"
            "    'user_feedback':      user_feedback,\n",
            1,
        )
    if "'user_feedback':" not in writes[writes.find("MERGE_KEYS = {") :]:
        writes = writes.replace(
            "    'agent_performance':  ['ConversationTranscriptId'],\n",
            "    'agent_performance':  ['ConversationTranscriptId'],\n"
            "    'user_feedback':      ['Feedback Event Key'],\n",
            1,
        )
    writes = writes.replace(
        "    'user_feedback':      ['Feedback Id'],",
        "    'user_feedback':      ['Feedback Event Key'],",
    )
    writes = writes.replace(
        "    table = f'{OUTPUT_PREFIX}.{name}'",
        "    table = f'{OUTPUT_PREFIX}.{name}' if OUTPUT_PREFIX else name",
    )
    old_merge_loop = """    if WRITE_MODE == 'merge':
        _how = 'merge(no-rows)'
        _chunks = 0
        for _i in range(0, len(_pdf_str), _chunk_rows):
            _part = _pdf_str.iloc[_i:_i + _chunk_rows]
            _sdf_part = spark.createDataFrame(_part, schema=schema)
            _how = _merge_delta(_sdf_part, name, table)
            _chunks += 1
"""
    new_merge_loop = """    if WRITE_MODE == 'merge':
        _how = 'merge(no-rows)'
        _chunks = 0
        if len(_pdf_str) == 0 and not spark.catalog.tableExists(table):
            (spark.createDataFrame([], schema=schema)
                .write.mode('append')
                .option('mergeSchema', 'true')
                .option('delta.columnMapping.mode', 'name')
                .option('delta.minReaderVersion', '2')
                .option('delta.minWriterVersion', '5')
                .format('delta').saveAsTable(table))
            _how = 'append(empty-first-load)'
            _chunks = 1
        else:
            for _i in range(0, len(_pdf_str), _chunk_rows):
                _part = _pdf_str.iloc[_i:_i + _chunk_rows]
                _sdf_part = spark.createDataFrame(_part, schema=schema)
                _how = _merge_delta(_sdf_part, name, table)
                _chunks += 1
"""
    writes = writes.replace(old_merge_loop, new_merge_loop)
    writes = writes.replace(
        "Done. Six Delta tables written.",
        "Done. Seven Delta tables written.",
    )
    notebook["cells"][27]["source"] = writes.splitlines(True)
    compile(config, "fabric_config", "exec")
    compile(helpers, "fabric_helpers", "exec")
    compile(sessions, "fabric_sessions", "exec")
    compile(performance, "fabric_agent_performance", "exec")
    compile(writes, "fabric_writes", "exec")
    path.write_text(json.dumps(notebook, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")


def patch_fabric_feedback_query(expression: str) -> str:
    feedback_columns = (
        "Feedback Event Key",
        "Conversation Id",
        "Agent Id",
        "Channel",
        "Feedback Source",
        "Feedback Verdict",
        "Match Status",
    )

    def normalize_empty_table(match: re.Match) -> str:
        columns = re.findall(r'"([^"]+)"', match.group(1))
        deduplicated = list(dict.fromkeys(columns))
        for column in feedback_columns:
            if column not in deduplicated:
                deduplicated.append(column)
        encoded = ", ".join(json.dumps(column) for column in deduplicated)
        return f"EmptyTable({{{encoded}}})"

    expression = re.sub(
        r"EmptyTable\(\{([^}]*)\}\)",
        normalize_empty_table,
        expression,
    )
    rename_marker = '        {"Additional Metadata", "AdditionalMetadata"}'
    rename_block = '''        {"Additional Metadata", "AdditionalMetadata"},
        {"Feedback Event Key", "FeedbackEventKey"},
        {"Conversation Id", "ConversationId"},
        {"Agent Id", "AgentId"},
        {"Feedback Source", "FeedbackSource"},
        {"Feedback Verdict", "FeedbackVerdict"},
        {"Match Status", "MatchStatus"}'''
    if "FeedbackEventKey" not in expression:
        expression = expression.replace(rename_marker, rename_block, 1)
    selected_marker = '"AiAgentType"})'
    selected_replacement = (
        '"AiAgentType", "FeedbackEventKey", "ConversationId", "AgentId", "Channel", '
        '"FeedbackSource", "FeedbackVerdict", "MatchStatus"}, MissingField.UseNull)'
    )
    if '"FeedbackEventKey"' not in expression[expression.rfind("Selected =") :]:
        expression = expression.replace(selected_marker, selected_replacement, 1)
    return expression


def patch_fabric_pbit(source: Path, destination: Path) -> None:
    with zipfile.ZipFile(source, "r") as archive:
        infos = archive.infolist()
        parts = {info.filename: archive.read(info.filename) for info in infos}
    schema = json.loads(parts["DataModelSchema"].decode("utf-16-le"))
    model = schema["model"]
    table = next(table for table in model["tables"] if table["name"] == "ProductFeedback")
    source_obj = table["partitions"][0]["source"]
    original = source_obj["expression"]
    expression = "\n".join(original) if isinstance(original, list) else original
    expression = patch_fabric_feedback_query(expression)
    source_obj["expression"] = expression.splitlines() if isinstance(original, list) else expression
    add_model_columns(
        table,
        FEEDBACK_DIAGNOSTIC_COLUMNS,
        "https://github.com/microsoft/ESS/fabric-feedback",
    )
    parts["DataModelSchema"] = json.dumps(schema, ensure_ascii=False, separators=(",", ":")).encode("utf-16-le")
    raw = parts["UnappliedChanges"].decode("utf-16-le")
    raw = replace_query_text_raw(raw, "ProductFeedback", patch_fabric_feedback_query)
    json.loads(raw)
    parts["UnappliedChanges"] = raw.encode("utf-16-le")
    destination.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(destination, "w", zipfile.ZIP_DEFLATED) as archive:
        for info in infos:
            archive.writestr(info, parts[info.filename])


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv-pbit", type=Path, required=True)
    parser.add_argument("--dataverse-pbit", type=Path, required=True)
    parser.add_argument("--fabric-pbit", type=Path, required=True)
    parser.add_argument("--fabric-notebook", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()

    patch_direct_pbit(args.csv_pbit, args.output_dir / args.csv_pbit.name)
    patch_direct_pbit(args.dataverse_pbit, args.output_dir / args.dataverse_pbit.name)
    patch_fabric_notebook(args.fabric_notebook)
    patch_fabric_pbit(args.fabric_pbit, args.output_dir / args.fabric_pbit.name)
    print(json.dumps({"outputDir": str(args.output_dir), "status": "ok"}, indent=2))


if __name__ == "__main__":
    main()
