import argparse
import csv
import json
import re
import uuid
import zipfile
from pathlib import Path

from topic_classifier import CLASSIFIER_VERSION

DIAGNOSTIC_COLUMNS = (
    ("TopicMatchedTerms", "string"),
    ("TopicMatchScore", "double"),
    ("TopicConfidence", "double"),
    ("TopicAmbiguous", "boolean"),
    ("TopicLanguage", "string"),
    ("TopicRuleSource", "string"),
    ("TopicClassifierVersion", "string"),
)
OVERRIDES_PARAMETER = "Customer Topic Overrides JSON (optional)"
OVERRIDES_QUERY = "CustomerTopicRules"
OVERRIDES_PARAMETER_LINEAGE = str(
    uuid.uuid5(uuid.NAMESPACE_URL, "https://github.com/microsoft/ESS/parameters/customer-topic-overrides-json")
)
OVERRIDES_QUERY_LINEAGE = str(
    uuid.uuid5(uuid.NAMESPACE_URL, "https://github.com/microsoft/ESS/queries/customer-topic-rules")
)
OVERRIDES_PARAMETER_EXPRESSION = (
    'null meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=false]'
)
OVERRIDES_PARAMETER_DESCRIPTION = (
    "Optional. Paste the contents of customer-topic-overrides.json generated by tools/ess_topic_tuner.py. "
    "Leave blank to use only the built-in taxonomy."
)


def m_string(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def load_taxonomy(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))

    required = {"Locale", "Vertical", "CanonicalTopic", "Keywords", "Exclusions", "Priority"}
    if not rows or set(rows[0]) != required:
        raise ValueError(f"Taxonomy columns must be exactly: {sorted(required)}")

    for row in rows:
        row["Priority"] = int(row["Priority"])
        if not row["Keywords"].strip():
            raise ValueError(f"Taxonomy rule has no keywords: {row}")
    return rows


def build_topic_rules(rows: list[dict[str, str]]) -> str:
    values = []
    for row in rows:
        values.append(
            "            {"
            + ", ".join(
                [
                    m_string(row["Locale"].strip().lower()),
                    m_string(row["Vertical"].strip()),
                    m_string(row["CanonicalTopic"].strip()),
                    m_string(row["Keywords"].strip()),
                    m_string(row["Exclusions"].strip()),
                    str(row["Priority"]),
                    m_string("BuiltIn"),
                ]
            )
            + "}"
        )

    return """// Shared, customer-neutral multilingual taxonomy.
// Source: taxonomy/topics-taxonomy.csv
let
    raw = #table(
        type table [
            Locale = text,
            Vertical = text,
            CanonicalTopic = text,
            Keywords = text,
            Exclusions = text,
            Priority = Int64.Type,
            RuleSource = text
        ],
        {
%s
        }
    ),
    combined = Table.Combine({raw, CustomerTopicRules}),
    valid = Table.SelectRows(
        combined,
        each [Vertical] <> null and Text.Trim([Vertical]) <> ""
          and [CanonicalTopic] <> null and Text.Trim([CanonicalTopic]) <> ""
          and [Keywords] <> null and Text.Trim([Keywords]) <> ""
    )
in
    Table.Sort(valid, {{"Priority", Order.Descending}, {"CanonicalTopic", Order.Ascending}})
""" % ",\n".join(values)


def build_customer_topic_rules() -> str:
    return f'''let
    Empty = #table(
        type table [
            Locale = text,
            Vertical = text,
            CanonicalTopic = text,
            Keywords = text,
            Exclusions = text,
            Priority = Int64.Type
        ],
        {{}}
    ),
    RawValue = try Text.From(#"{OVERRIDES_PARAMETER}") otherwise "",
    RawText = if RawValue = null then "" else Text.Trim(RawValue),
    Parsed =
        if RawText = "" then {{}}
        else try Json.Document(Text.ToBinary(RawText, TextEncoding.Utf8))
             otherwise error "Customer Topic Overrides JSON is invalid. Regenerate customer-topic-overrides.json with ess_topic_tuner.py.",
    Checked =
        if not Value.Is(Parsed, type list) then
            error "Customer Topic Overrides JSON must contain a JSON array."
        else Parsed,
    Records = List.Select(Checked, each Value.Is(_, type record)),
    AsTable =
        if List.IsEmpty(Records) then Empty
        else Table.FromRecords(
            Records,
            type table [
                Locale = nullable text,
                Vertical = nullable text,
                CanonicalTopic = nullable text,
                Keywords = nullable text,
                Exclusions = nullable text,
                Priority = nullable number
            ],
            MissingField.UseNull
        ),
    Typed = Table.TransformColumnTypes(
        AsTable,
        {{
            {{"Locale", type text}},
            {{"Vertical", type text}},
            {{"CanonicalTopic", type text}},
            {{"Keywords", type text}},
            {{"Exclusions", type text}},
            {{"Priority", Int64.Type}}
        }}
    ),
    NormalizedLocale = Table.TransformColumns(
        Typed,
        {{{{"Locale", each if _ = null or Text.Trim(_) = "" then "*" else Text.Lower(Text.Trim(_)), type text}}}}
    ),
    WithSource = Table.AddColumn(NormalizedLocale, "RuleSource", each "Customer", type text)
in
    WithSource
'''


def build_classifier() -> str:
    return f'''let
    Rules = List.Buffer(Table.ToRecords(TopicRules)),
    ClassifierVersion = {m_string(CLASSIFIER_VERSION)},
    Separators = " #(tab)#(cr)#(lf).,;:!?()[]{{}}<>/\\-_+=*&^%$#@~`'""",

    NormalizeText = (value as nullable text) as text =>
        let
            lower = if value = null then "" else Text.Lower(Text.From(value)),
            tokens = List.Select(
                List.Transform(Text.SplitAny(lower, Separators), Text.Trim),
                each _ <> ""
            )
        in
            Text.Combine(tokens, " "),

    LocalePrefix = (locale as nullable text) as text =>
        let
            normalized = Text.Lower(Text.Trim(if locale = null then "" else Text.From(locale)))
        in
            if Text.Length(normalized) >= 2 then Text.Start(normalized, 2) else normalized,

    ContainsTerm = (normalizedText as text, term as text, language as text) as logical =>
        let
            normalizedTerm = NormalizeText(term)
        in
            if normalizedTerm = "" then false
            else if language = "zh" then Text.Contains(normalizedText, normalizedTerm, Comparer.OrdinalIgnoreCase)
            else Text.Contains(" " & normalizedText & " ", " " & normalizedTerm & " ", Comparer.OrdinalIgnoreCase),

    TermWeight = (term as text, language as text) as number =>
        let
            normalizedTerm = NormalizeText(term),
            wordCount = List.Count(List.Select(Text.Split(normalizedTerm, " "), each _ <> ""))
        in
            if language = "zh" then (if Text.Length(normalizedTerm) >= 4 then 3 else 2)
            else if wordCount >= 2 then 3
            else if Text.Length(normalizedTerm) <= 2 then 1
            else 2,

    ClassifyTopic = (inputText as nullable text, optional inputLocale as nullable text) as record =>
        let
            normalizedText = NormalizeText(inputText),
            language = LocalePrefix(inputLocale),
            eligibleRules = List.Select(Rules, each [Locale] = "*" or [Locale] = language),
            scoredRules = List.Transform(
                eligibleRules,
                (rule) =>
                    let
                        keywords = List.Select(
                            List.Transform(Text.Split(Text.From(rule[Keywords]), "|"), Text.Trim),
                            each _ <> ""
                        ),
                        exclusions = List.Select(
                            List.Transform(Text.Split(Text.From(rule[Exclusions]), "|"), Text.Trim),
                            each _ <> ""
                        ),
                        hits = List.Select(keywords, each ContainsTerm(normalizedText, _, language)),
                        excluded = List.AnyTrue(List.Transform(exclusions, each ContainsTerm(normalizedText, _, language))),
                        score = if excluded then 0 else List.Sum(List.Transform(hits, each TermWeight(_, language)))
                    in
                        [Rule = rule, Hits = hits, Score = score]
            ),
            positiveRules = List.Select(scoredRules, each [Score] > 0),
            sortedRules = List.Sort(
                positiveRules,
                (left, right) =>
                    if left[Score] > right[Score] then -1
                    else if left[Score] < right[Score] then 1
                    else if left[Rule][Priority] > right[Rule][Priority] then -1
                    else if left[Rule][Priority] < right[Rule][Priority] then 1
                    else Value.Compare(left[Rule][CanonicalTopic], right[Rule][CanonicalTopic])
            ),
            top = List.First(sortedRules, null),
            topScore = if top = null then 0 else top[Score],
            topPriority = if top = null then null else top[Rule][Priority],
            tiedRules = if top = null then {{}} else List.Select(
                sortedRules,
                each [Score] = topScore and [Rule][Priority] = topPriority
            ),
            tiedTopics = List.Distinct(List.Transform(
                tiedRules,
                each [Rule][Vertical] & "|" & [Rule][CanonicalTopic]
            )),
            ambiguous = List.Count(tiedTopics) > 1,
            chosen = if ambiguous then null else top,
            ruleSource = if chosen = null then null else chosen[Rule][RuleSource],
            resultVersion =
                if ruleSource = "Customer" then ClassifierVersion & "+CUSTOMER"
                else ClassifierVersion,
            confidence =
                if chosen = null then (if ambiguous then 0.4 else 0.0)
                else if topScore >= 6 then 0.98
                else if topScore >= 4 then 0.93
                else if topScore >= 2 then 0.85
                else 0.70,
            result =
                if normalizedText = "" then [
                    Topic = "No User Intent",
                    Vertical = "System-Init",
                    MatchedTerms = null,
                    Score = 0.0,
                    Confidence = 1.0,
                    Ambiguous = false,
                    Language = language,
                    RuleSource = null,
                    ClassifierVersion = ClassifierVersion
                ]
                else if chosen = null then [
                    Topic = "Other / Uncategorized",
                    Vertical = "Unknown",
                    MatchedTerms = if ambiguous then Text.Combine(
                        List.Distinct(List.Combine(List.Transform(tiedRules, each [Hits]))),
                        " | "
                    ) else null,
                    Score = Number.From(topScore),
                    Confidence = confidence,
                    Ambiguous = ambiguous,
                    Language = language,
                    RuleSource = null,
                    ClassifierVersion = ClassifierVersion
                ]
                else [
                    Topic = chosen[Rule][CanonicalTopic],
                    Vertical = chosen[Rule][Vertical],
                    MatchedTerms = Text.Combine(chosen[Hits], " | "),
                    Score = Number.From(chosen[Score]),
                    Confidence = confidence,
                    Ambiguous = false,
                    Language = language,
                    RuleSource = ruleSource,
                    ClassifierVersion = resultVersion
                ]
        in
            result
in
    ClassifyTopic
'''


def build_derived_block() -> str:
    return f"""    // Derived-topic fallback: native-first, then the shared locale-aware classifier.
    WithClass = Table.AddColumn(ExcludeTestConversations, "_TopicClass",
        each if [PrimaryTopic] = null
                or Text.Trim(Text.From([PrimaryTopic])) = ""
                or [PrimaryTopic] = "No Topic Detected"
                or [PrimaryTopic] = "No User Intent"
                or [PrimaryTopic] = "Other / Uncategorized"
             then ClassifyTopic([FirstUserMessage], [Locale])
             else [
                Topic = [PrimaryTopic],
                Vertical = "Native",
                MatchedTerms = null,
                Score = null,
                Confidence = 1.0,
                Ambiguous = false,
                Language = if [Locale] = null then "" else Text.Lower(Text.Start(Text.From([Locale]), 2)),
                RuleSource = "Native",
                ClassifierVersion = "Native"
             ],
        type record),
    WithDerivedPrimaryTopic = Table.AddColumn(WithClass, "DerivedPrimaryTopic",
        each [_TopicClass][Topic], type nullable text),
    WithDerivedVertical = Table.AddColumn(WithDerivedPrimaryTopic, "DerivedVertical",
        each [_TopicClass][Vertical], type nullable text),
    WithTopicMatchedTerms = Table.AddColumn(WithDerivedVertical, "TopicMatchedTerms",
        each [_TopicClass][MatchedTerms], type nullable text),
    WithTopicMatchScore = Table.AddColumn(WithTopicMatchedTerms, "TopicMatchScore",
        each [_TopicClass][Score], type nullable number),
    WithTopicConfidence = Table.AddColumn(WithTopicMatchScore, "TopicConfidence",
        each [_TopicClass][Confidence], type nullable number),
    WithTopicAmbiguous = Table.AddColumn(WithTopicConfidence, "TopicAmbiguous",
        each [_TopicClass][Ambiguous], type logical),
    WithTopicLanguage = Table.AddColumn(WithTopicAmbiguous, "TopicLanguage",
        each [_TopicClass][Language], type nullable text),
    WithTopicRuleSource = Table.AddColumn(WithTopicLanguage, "TopicRuleSource",
        each [_TopicClass][RuleSource], type nullable text),
    WithTopicClassifierVersion = Table.AddColumn(WithTopicRuleSource, "TopicClassifierVersion",
        each [_TopicClass][ClassifierVersion], type nullable text),
    WithTopicSource = Table.AddColumn(WithTopicClassifierVersion, "TopicSource",
        each if [PrimaryTopic] <> null
                and Text.Trim(Text.From([PrimaryTopic])) <> ""
                and [PrimaryTopic] <> "No Topic Detected"
                and [PrimaryTopic] <> "No User Intent"
                and [PrimaryTopic] <> "Other / Uncategorized" then "Native"
             else if [UserMessageCount] <> null and [UserMessageCount] > 0 then "Derived"
             else "System-Init",
        type text),
"""


def replace_derived_block(expression: str) -> str:
    start_markers = (
        "    // Derived-topic fallback:",
        "    // ── Derived-topic fallback",
    )
    end_marker = "    WithIsEngaged ="
    start = next((position for marker in start_markers if (position := expression.find(marker)) >= 0), -1)
    end = expression.find(end_marker, start)
    if start < 0 or end < 0:
        raise ValueError("Could not locate the derived-topic block")
    return expression[:start] + build_derived_block() + expression[end:]


def set_expression(model: dict, name: str, value: str) -> None:
    expression = next((item for item in model["expressions"] if item["name"] == name), None)
    if expression is None:
        raise ValueError(f"Model expression not found: {name}")
    expression["expression"] = value


def upsert_expression(model: dict, expression: dict, before: str) -> None:
    existing = next((item for item in model["expressions"] if item["name"] == expression["name"]), None)
    if existing:
        existing.update(expression)
        return
    index = next(index for index, item in enumerate(model["expressions"]) if item["name"] == before)
    model["expressions"].insert(index, expression)


def insert_query_raw(raw: str, query: dict) -> str:
    document = json.loads(raw)
    if any(item["name"] == query["name"] for item in document["queries"]):
        return raw
    match = re.search(r'"queries"\s*:\s*\[', raw)
    if not match:
        raise ValueError("Unapplied query collection not found")
    encoded = json.dumps(query, ensure_ascii=False, separators=(",", ":")) + ","
    return raw[: match.end()] + encoded + raw[match.end() :]


def patch_partition(model: dict) -> None:
    table = next(item for item in model["tables"] if item["name"] == "Agent Performance")
    source = table["partitions"][0]["source"]
    original = source["expression"]
    text = "\n".join(original) if isinstance(original, list) else original
    updated = replace_derived_block(text)
    source["expression"] = updated.splitlines() if isinstance(original, list) else updated

    existing = {column["name"] for column in table.get("columns", [])}
    for name, data_type in DIAGNOSTIC_COLUMNS:
        if name in existing:
            continue
        table["columns"].append(
            {
                "name": name,
                "dataType": data_type,
                "sourceColumn": name,
                "lineageTag": str(uuid.uuid5(uuid.NAMESPACE_URL, f"https://github.com/microsoft/ESS/{name}")),
                "summarizeBy": "none",
                "annotations": [{"name": "SummarizationSetBy", "value": "Automatic"}],
            }
        )


def replace_query_text_raw(raw: str, query_name: str, transform) -> str:
    document = json.loads(raw)
    query = next((item for item in document["queries"] if item["name"] == query_name), None)
    if query is None:
        raise ValueError(f"Unapplied query not found: {query_name}")
    old_value = query["text"]
    old_text = "\n".join(old_value) if isinstance(old_value, list) else old_value
    new_text = transform(old_text)
    new_value = new_text.splitlines() if isinstance(old_value, list) else new_text
    old_encoded = json.dumps(old_value, ensure_ascii=False, separators=(",", ":"))
    new_encoded = json.dumps(new_value, ensure_ascii=False, separators=(",", ":"))

    query_start = raw.find(json.dumps(query_name, ensure_ascii=False))
    value_start = raw.find('"text":' + old_encoded, query_start)
    if value_start < 0:
        raise ValueError(f"Raw unapplied query payload not found: {query_name}")
    value_start += len('"text":')
    return raw[:value_start] + new_encoded + raw[value_start + len(old_encoded) :]


def patch_pbit(source: Path, destination: Path, topic_rules: str, classifier: str) -> dict:
    with zipfile.ZipFile(source, "r") as archive:
        infos = archive.infolist()
        parts = {info.filename: archive.read(info.filename) for info in infos}

    schema = json.loads(parts["DataModelSchema"].decode("utf-16-le"))
    model = schema["model"]
    customer_topic_rules = build_customer_topic_rules()
    upsert_expression(
        model,
        {
            "name": OVERRIDES_PARAMETER,
            "description": OVERRIDES_PARAMETER_DESCRIPTION,
            "kind": "m",
            "expression": OVERRIDES_PARAMETER_EXPRESSION,
            "lineageTag": OVERRIDES_PARAMETER_LINEAGE,
            "annotations": [
                {"name": "PBI_NavigationStepName", "value": "Navigation"},
                {"name": "PBI_ResultType", "value": "Text"},
            ],
        },
        "TopicRules",
    )
    upsert_expression(
        model,
        {
            "name": OVERRIDES_QUERY,
            "kind": "m",
            "expression": customer_topic_rules,
            "lineageTag": OVERRIDES_QUERY_LINEAGE,
            "annotations": [{"name": "PBI_ResultType", "value": "List"}],
        },
        "TopicRules",
    )
    set_expression(model, "TopicRules", topic_rules)
    set_expression(model, "ClassifyTopic", classifier)
    patch_partition(model)
    parts["DataModelSchema"] = json.dumps(schema, ensure_ascii=False, separators=(",", ":")).encode("utf-16-le")

    unapplied_raw = parts["UnappliedChanges"].decode("utf-16-le")
    unapplied_raw = insert_query_raw(
        unapplied_raw,
        {
            "name": OVERRIDES_PARAMETER,
            "lineageTag": OVERRIDES_PARAMETER_LINEAGE,
            "description": OVERRIDES_PARAMETER_DESCRIPTION,
            "navigationStepName": "Navigation",
            "text": [OVERRIDES_PARAMETER_EXPRESSION],
            "loadAsTableDisabled": True,
            "resultType": "Text",
            "isHidden": False,
        },
    )
    unapplied_raw = insert_query_raw(
        unapplied_raw,
        {
            "name": OVERRIDES_QUERY,
            "lineageTag": OVERRIDES_QUERY_LINEAGE,
            "text": customer_topic_rules.splitlines(),
            "loadAsTableDisabled": True,
            "resultType": "List",
            "isHidden": False,
        },
    )
    unapplied_raw = replace_query_text_raw(unapplied_raw, OVERRIDES_PARAMETER, lambda _: OVERRIDES_PARAMETER_EXPRESSION)
    unapplied_raw = replace_query_text_raw(unapplied_raw, OVERRIDES_QUERY, lambda _: customer_topic_rules)
    unapplied_raw = replace_query_text_raw(unapplied_raw, "TopicRules", lambda _: topic_rules)
    unapplied_raw = replace_query_text_raw(unapplied_raw, "ClassifyTopic", lambda _: classifier)
    unapplied_raw = replace_query_text_raw(unapplied_raw, "Agent Performance", replace_derived_block)
    json.loads(unapplied_raw)
    parts["UnappliedChanges"] = unapplied_raw.encode("utf-16-le")

    destination.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(destination, "w", zipfile.ZIP_DEFLATED) as archive:
        for info in infos:
            archive.writestr(info, parts[info.filename])

    with zipfile.ZipFile(destination, "r") as archive:
        json.loads(archive.read("DataModelSchema").decode("utf-16-le"))
        json.loads(archive.read("UnappliedChanges").decode("utf-16-le"))

    return {
        "source": str(source),
        "destination": str(destination),
        "size": destination.stat().st_size,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--taxonomy", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("pbits", type=Path, nargs="+")
    args = parser.parse_args()

    rows = load_taxonomy(args.taxonomy)
    topic_rules = build_topic_rules(rows)
    classifier = build_classifier()

    results = []
    for source in args.pbits:
        destination = args.output_dir / source.name
        results.append(patch_pbit(source, destination, topic_rules, classifier))

    print(
        json.dumps(
            {
                "classifierVersion": CLASSIFIER_VERSION,
                "taxonomyRules": len(rows),
                "artifacts": results,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
